#!/usr/bin/env python3
"""setup_bots.py — Interactive setup wizard for configuring multiple Telegram crypto swap bots.

Run from the repository root:
    python3 setup_bots.py

Pure Python 3 — no external dependencies beyond the standard library.
"""

import os
import re
import sys
import datetime

# ---------------------------------------------------------------------------
# ANSI colour helpers
# ---------------------------------------------------------------------------
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
CYAN = "\033[96m"
BOLD = "\033[1m"
RESET = "\033[0m"


def ok(msg: str) -> None:
    print(f"{GREEN}✅ {msg}{RESET}")


def warn(msg: str) -> None:
    print(f"{YELLOW}⚠️  {msg}{RESET}")


def err(msg: str) -> None:
    print(f"{RED}❌ {msg}{RESET}")


def info(msg: str) -> None:
    print(f"{CYAN}{msg}{RESET}")


def header(msg: str) -> None:
    print(f"\n{BOLD}{msg}{RESET}")


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
MAX_BOTS = 7
CONFIG_DIR = "config"
CONFIG_PATH = os.path.join(CONFIG_DIR, "config.toml")

SUPPORTED_LANGUAGES = ["en", "it", "ru", "uk", "zh_cn", "he", "es_mx", "pt_br", "hi"]

# Coins: display name -> TOML key (quoted when it contains a hyphen)
COINS = [
    ("BTC",        "BTC",          "bitcoin"),
    ("LTC",        "LTC",          "litecoin"),
    ("XMR",        "XMR",          "monero"),
    ("USDT-TRC20", '"USDT-TRC20"', "tether"),
    ("ZCASH",      "ZCASH",        "zcash"),
]

# Regex for a valid Telegram bot token: DIGITS:ALPHANUMERIC
BOT_TOKEN_RE = re.compile(r"^\d{8,12}:[A-Za-z0-9_-]{35,}$")


# ---------------------------------------------------------------------------
# Input helpers
# ---------------------------------------------------------------------------
def prompt(question: str, default: str = "") -> str:
    """Ask a question; return the stripped answer (or *default* if empty)."""
    if default:
        display = f"{question} [{default}]: "
    else:
        display = f"{question}: "
    try:
        answer = input(display).strip()
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(0)
    return answer if answer else default


def prompt_required(question: str) -> str:
    """Ask a question that must not be empty."""
    while True:
        answer = prompt(question)
        if answer:
            return answer
        err("This field is required.")


def prompt_int(question: str, default: int, min_val: int, max_val: int) -> int:
    """Ask for an integer within [min_val, max_val]."""
    while True:
        raw = prompt(question, str(default))
        try:
            value = int(raw)
        except ValueError:
            err(f"Please enter a whole number between {min_val} and {max_val}.")
            continue
        if min_val <= value <= max_val:
            return value
        err(f"Value must be between {min_val} and {max_val}.")


def prompt_float(question: str, default: float) -> float:
    """Ask for a non-negative float."""
    while True:
        raw = prompt(question, str(default))
        try:
            value = float(raw)
        except ValueError:
            err("Please enter a valid number.")
            continue
        if value < 0:
            err("Value must not be negative.")
            continue
        return value


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------
def validate_token(token: str) -> bool:
    """Return True if *token* looks like a Telegram bot token."""
    return bool(BOT_TOKEN_RE.match(token))


def warn_placeholder(label: str, address: str) -> None:
    """Warn if *address* still contains placeholder text."""
    if "YOUR_" in address.upper() or not address:
        warn(f"{label} still contains a placeholder value: '{address}'")


# ---------------------------------------------------------------------------
# Config generation
# ---------------------------------------------------------------------------
def build_config(
    bots: list,
    deposit_addresses: dict,
    fee_addresses: dict,
    coingecko_api_key: str,
    language: str,
    currency: str,
    currency_symbol: str,
    currency_exp: int,
    min_usd: float,
    max_usd: float,
    fee_pct: float,
) -> str:
    """Return the full content of config.toml as a string."""

    lines = []

    # ---- [Language] --------------------------------------------------------
    lines += [
        "# greed configuration file — generated by setup_bots.py",
        "",
        "# Language parameters",
        "[Language]",
        f'enabled_languages = {SUPPORTED_LANGUAGES!r}'.replace("'", '"'),
        f'default_language = "{language}"',
        'fallback_language = "en"',
        "",
    ]

    # ---- [Database] --------------------------------------------------------
    lines += [
        "# Database parameters",
        "[Database]",
        'engine = "sqlite:///database.sqlite"',
        "",
    ]

    # ---- [Telegram] --------------------------------------------------------
    # Use the first bot's token as the main Telegram token.
    main_token = bots[0]["token"] if bots else "123456789:YOUR_TOKEN_GOES_HERE_______________"
    lines += [
        "# Telegram bot parameters",
        "[Telegram]",
        f'token = "{main_token}"',
        "conversation_timeout = 7200",
        "long_polling_timeout = 30",
        "timed_out_pause = 1",
        "error_pause = 5",
        "con_pool_size = 10",
        "",
    ]

    # ---- [Payments] --------------------------------------------------------
    lines += [
        "# General payment settings",
        "[Payments]",
        f'currency = "{currency}"',
        f"currency_exp = {currency_exp}",
        f'currency_symbol = "{currency_symbol}"',
        "",
        "# Cash payment settings",
        "[Payments.Cash]",
        "enable_pay_with_cash = false",
        "enable_create_transaction = false",
        "",
        "# Credit card payment settings",
        "[Payments.CreditCard]",
        'credit_card_token = ""',
        "min_amount = 1000",
        "max_amount = 1000000",
        "payment_presets = [10.00, 25.00, 50.00, 100.00]",
        "tip_presets = []",
        "max_tip_amount = 0",
        "fee_percentage = 2.9",
        "fee_fixed = 30",
        "name_required = true",
        "email_required = true",
        "phone_required = true",
        "",
    ]

    # ---- [Appearance] ------------------------------------------------------
    lines += [
        "# Bot appearance settings",
        "[Appearance]",
        "full_order_info = false",
        "refill_on_checkout = true",
        "display_welcome_message = true",
        "",
    ]

    # ---- [Logging] ---------------------------------------------------------
    lines += [
        "# Logging settings",
        "[Logging]",
        'format = "{asctime} | {threadName} | {name} | {message}"',
        'level = "INFO"',
        "",
    ]

    # ---- [CryptoSwap] ------------------------------------------------------
    # Build optional api_key line
    api_key_line = f'api_key = "{coingecko_api_key}"' if coingecko_api_key else "# api_key = \"\"  # optional CoinGecko API key"

    lines += [
        "# Crypto swap settings",
        "[CryptoSwap]",
        "enabled = true",
        'price_api = "https://api.coingecko.com/api/v3"',
        api_key_line,
        "cache_ttl = 60",
        f"fee_percentage = {fee_pct}",
        "quote_timeout = 60",
        f"min_usd = {min_usd}",
        f"max_usd = {max_usd}",
        "",
        "# CoinGecko ID mappings for supported coins",
        "[CryptoSwap.Coins]",
    ]
    for display_name, toml_key, cg_id in COINS:
        lines.append(f'{toml_key} = "{cg_id}"')

    lines += [
        "",
        "# Fee collection addresses — one per coin",
        "[CryptoSwap.FeeAddresses]",
    ]
    for display_name, toml_key, _ in COINS:
        addr = fee_addresses.get(display_name, "")
        lines.append(f'{toml_key} = "{addr}"')

    lines += [
        "",
        "# Deposit addresses shown to customers — one per coin",
        "[CryptoSwap.DepositAddresses]",
    ]
    for display_name, toml_key, _ in COINS:
        addr = deposit_addresses.get(display_name, "")
        lines.append(f'{toml_key} = "{addr}"')

    lines += [""]

    # ---- [Bots] ------------------------------------------------------------
    lines += [
        "# Multi-bot configuration",
        "[Bots]",
        "max_workers_per_bot = 50",
        "worker_idle_timeout = 1800",
        "",
    ]

    for i, bot in enumerate(bots, start=1):
        key = f"bot{i}"
        lines += [
            f"[Bots.{key}]",
            f'token = "{bot["token"]}"',
            "enabled = true",
            f'name = "{bot["name"]}"',
            f'database = "sqlite:///{key}.sqlite"',
            f'directory = "{bot["name"]}-TG-Bot"',
            "",
        ]

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Main wizard
# ---------------------------------------------------------------------------
def main():
    print(f"\n{BOLD}🤖 Greed Multi-Bot Setup Wizard{RESET}")
    print("=" * 32)
    print("This wizard will create config/config.toml for you.")
    print("Press Ctrl-C at any time to abort.\n")

    # ------------------------------------------------------------------
    # Step 1 — Number of bots
    # ------------------------------------------------------------------
    header("Step 1: Bot count")
    num_bots = prompt_int(
        f"How many bots would you like to configure? (1–{MAX_BOTS})",
        default=1, min_val=1, max_val=MAX_BOTS,
    )

    # ------------------------------------------------------------------
    # Step 2 — Per-bot tokens and names
    # ------------------------------------------------------------------
    bots = []
    for i in range(1, num_bots + 1):
        header(f"--- Bot {i} ---")
        default_name = f"ShopBot-{i}"

        # Token
        while True:
            token = prompt_required(f"Telegram bot token (from @BotFather)")
            if validate_token(token):
                break
            err("Token format looks wrong. Expected: DIGITS:ALPHANUMERIC (e.g. 123456789:ABCdef…)")
            warn("Re-enter the token.")

        # Name
        name = prompt(f"Bot display name", default=default_name)

        bots.append({"token": token, "name": name})

    # ------------------------------------------------------------------
    # Step 3 — Crypto deposit addresses
    # ------------------------------------------------------------------
    header("--- Crypto Deposit Addresses ---")
    info("These are the wallet addresses customers will send funds to.")
    deposit_addresses = {}
    for display_name, _, _ in COINS:
        addr = prompt_required(f"{display_name} deposit address")
        warn_placeholder(f"{display_name} deposit address", addr)
        deposit_addresses[display_name] = addr

    # ------------------------------------------------------------------
    # Step 4 — Fee addresses (default to deposit addresses)
    # ------------------------------------------------------------------
    header("--- Fee Addresses (press Enter to reuse deposit address) ---")
    info("The address where swap fees are collected. Defaults to the deposit address.")
    fee_addresses = {}
    for display_name, _, _ in COINS:
        default_addr = deposit_addresses[display_name]
        addr = prompt(f"{display_name} fee address", default=default_addr)
        fee_addresses[display_name] = addr

    # ------------------------------------------------------------------
    # Step 5 — Swap settings
    # ------------------------------------------------------------------
    header("--- Swap Settings ---")
    min_usd = prompt_float("Minimum swap amount (USD)", default=1000.0)
    max_usd = prompt_float("Maximum swap amount (USD)", default=1000000.0)
    if max_usd < min_usd:
        warn("max_usd is less than min_usd — values have been swapped.")
        min_usd, max_usd = max_usd, min_usd
    fee_pct = prompt_float("Swap fee percentage", default=1.0)

    # ------------------------------------------------------------------
    # Step 6 — CoinGecko API key
    # ------------------------------------------------------------------
    header("--- CoinGecko API Key (optional) ---")
    info("Free tier works without a key. Paid key increases rate limits.")
    coingecko_api_key = prompt("CoinGecko API key (leave blank to skip)", default="")

    # ------------------------------------------------------------------
    # Step 7 — Language
    # ------------------------------------------------------------------
    header("--- Language ---")
    info(f"Supported languages: {', '.join(SUPPORTED_LANGUAGES)}")
    while True:
        language = prompt("Default language", default="en")
        if language in SUPPORTED_LANGUAGES:
            break
        err(f"'{language}' is not in the supported list. Please choose from: {', '.join(SUPPORTED_LANGUAGES)}")

    # ------------------------------------------------------------------
    # Step 8 — Currency
    # ------------------------------------------------------------------
    header("--- Currency Settings ---")
    currency = prompt("Currency ISO code", default="USD")
    currency_symbol = prompt("Currency symbol", default="$")
    currency_exp = prompt_int("Currency exponent (decimal places, usually 2)", default=2, min_val=0, max_val=8)

    # ------------------------------------------------------------------
    # Generate config
    # ------------------------------------------------------------------
    header("--- Generating Configuration ---")

    config_content = build_config(
        bots=bots,
        deposit_addresses=deposit_addresses,
        fee_addresses=fee_addresses,
        coingecko_api_key=coingecko_api_key,
        language=language,
        currency=currency,
        currency_symbol=currency_symbol,
        currency_exp=currency_exp,
        min_usd=min_usd,
        max_usd=max_usd,
        fee_pct=fee_pct,
    )

    # Backup existing config
    os.makedirs(CONFIG_DIR, exist_ok=True)
    if os.path.exists(CONFIG_PATH):
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_path = f"{CONFIG_PATH}.backup.{timestamp}"
        os.rename(CONFIG_PATH, backup_path)
        warn(f"Existing config backed up to: {backup_path}")

    # Write new config
    with open(CONFIG_PATH, "w", encoding="utf-8") as fh:
        fh.write(config_content)
    ok(f"Config written to {CONFIG_PATH}")

    # ------------------------------------------------------------------
    # Create bot directories
    # ------------------------------------------------------------------
    created_dirs = []
    for bot in bots:
        bot_dir = f"{bot['name']}-TG-Bot"
        os.makedirs(bot_dir, exist_ok=True)
        created_dirs.append(bot_dir)
    ok(f"Created directories: {', '.join(created_dirs)}")

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    header("=" * 32)
    ok(f"{num_bots} bot(s) configured and ready!")
    print()
    for i, bot in enumerate(bots, start=1):
        bot_dir = f"{bot['name']}-TG-Bot"
        print(f"  Bot {i}: {BOLD}{bot['name']}{RESET}  →  {bot_dir}/")
    print()
    enabled_coins = [c[0] for c in COINS if deposit_addresses.get(c[0])]
    info(f"Enabled coins: {', '.join(enabled_coins)}")
    print()
    print("Restart your bot service to apply the new configuration:")
    print(f"  {BOLD}sudo systemctl restart greed-bot{RESET}")
    print()


if __name__ == "__main__":
    main()
